name: Python CI

on: 
  push:
    branches:
      - main  # Run the workflow when code is pushed to the main branch.

jobs:
  test-python:
    runs-on: ubuntu-latest  # Use an Ubuntu machine to run tasks.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Check out your repository code.

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify Python version.

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest
